src/WorldOfBirds/WorldOfBirds/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using WorldOfBirds.Models;



namespace WorldOfBirds.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly MessageRepository _messageRepository = new MessageRepository();

        [HttpGet]
        public ViewResult Feedback()
        {            
            return View();
        }                

        [HttpPost] 
        public ActionResult Feedback(Message message)
        {
            if (ModelState.IsValid)
            {
                _messageRepository.SaveMessage(message);
                return View("Thanks", message);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);              
            }
        }
    }
}

src/WorldOfBirds/WorldOfBirds/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorldOfBirds.Models;

namespace WorldOfBirds.Controllers
{
    public class GalleryController : Controller
    {
        private readonly CategoryRepository _categoryRepository = new CategoryRepository();

        public ActionResult Gallery()
        {
            return View(_categoryRepository.GetBirdsCategories());
        }
	}
}

src/WorldOfBirds/WorldOfBirds/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="@Url.Content("~/Content/")bootstrap.min.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/")bootstrap-theme.min.css">

    @Scripts.Render("~/Scripts/ie-emulation-modes-warning.js")
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- Custom styles for this template -->
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
@Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/ie10-viewport-bug-workaround.js")
</body>
</html>

src/WorldOfBirds/WorldOfBirds/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @* Template Header Files*@
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="@Url.Content("~/Content/")bootstrap.min.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/")bootstrap-theme.min.css">
    <link href="@Url.Content("~/Content/")ie10-viewport-bug-workaround.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/")starter-template.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/")theme.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/")jumbotron.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/")signin.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/")style.css" rel="stylesheet">


    @Scripts.Render("~/Scripts/ie-emulation-modes-warning.js")
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- Custom styles for this template -->
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->


</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">МИР ПТИЦ</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Галерея", "Gallery", "Gallery")</li>
                    <li>@Html.ActionLink("Обратная связь", "Feedback", "Feedback")</li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>


    <div>
        @RenderBody()
    </div>
    <hr>
    <div class="container">
        <footer>
            <p>&copy; 2016 Company, Inc.</p>
        </footer>
    </div> <!-- /container -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/ie10-viewport-bug-workaround.js")

</body>


</html>